### ISSUE TITLE
on hover circle

### ISSUE THREAD

**Issue by chef-danny-d** [chef-danny-d/isaac#2]
on hover for icons in the nav a circle will appear. a ring like border of some kind to show hover animation.

**Comment by petercr** [comment]
Do you still want help with this? :thinking:

**Comment by chef-danny-d** [comment]
@petercr This is a super low priority but any help is appreciated. To give a little background: the effect that the I had in mind was on hover a circle would load from top to bottom not just a basic on:hover border. Will probably need to utilize ::before and ::after pseudo elements.

**Comment by petercr** [comment]
Ok cool that sounds like a neat little project :+1: 
You talking about the nav icons on the right hand side, correct?

**Comment by petercr** [comment]
So I was thinking that maybe we could apply a **gradient** background that goes from black to a blue color from top to bottom. And then have it `transition` to the opposite gradient, which would give the effect of going from from bottom to top, or the other way.
Anyways that's my plan, now I'm going to try to _implement_ it.. 🤔 😅 
But at least I've got a concept to work on. 👍

**Comment by chef-danny-d** [comment]
@petercr sounds dope. submit your PR once you get it done and i'll take a look at it. 🙂
